const Vehicle=require("../models/Vehicle");
const User=require("../models/User");
const DriverProfile=require("../models/DriverProfile");
const Trip=require("../models/Trip");
const Assignment=require("../models/Assignment");
const MaintenanceRecord=require("../models/MaintenanceRecord");
const MaintenanceWorkOrder=require("../models/MaintenanceWorkOrder");
const MaintenanceSchedule=require("../models/MaintenanceSchedule");
const FuelExpense=require("../models/FuelExpense");
const Expense=require("../models/Expense");
const TripExpense=require("../models/TripExpense");
const DriverExpense=require("../models/DriverExpense");
const TripTracking=require("../models/TripTracking");
const AuditLog=require("../models/AuditLog");
const oid=id=>require("mongoose").Types.ObjectId.isValid(id);
const dateRange=(q,field)=>{const f={};if(q.from){const d=new Date(q.from);if(!Number.isNaN(d.getTime()))f[field]={$gte:d};}if(q.to){const d=new Date(q.to);if(!Number.isNaN(d.getTime())){d.setHours(23,59,59,999);f[field]={...(f[field]||{}),$lte:d};}}return f;};
async function liveFleet(req,res){try{const vehicles=await Vehicle.find({}).select("registrationNumber vehicleNumber vehicleType status assignedDriver ownershipType").populate("assignedDriver","fullName phone").lean();const rows=await TripTracking.find({}).sort({recordedAt:-1}).limit(3000).populate("trip","tripId tripStatus pickupLocation destination").populate("vehicle","registrationNumber vehicleNumber vehicleType status").populate("driver","fullName phone").lean();const latest=new Map();for(const r of rows){const k=String(r.vehicle?._id||r.vehicle||r.trip?._id||r.trip||r._id);if(!latest.has(k))latest.set(k,r);}return res.json({success:true,vehicles:vehicles.map(v=>{const t=latest.get(String(v._id));return {...v,tracking:t||null,location:t?{latitude:t.latitude,longitude:t.longitude,currentLocation:t.currentLocation,speed:t.speed,recordedAt:t.recordedAt}:null};})});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load live fleet data."});}}
async function vehicleHistory(req,res){try{if(!oid(req.params.id))return res.status(400).json({success:false,message:"Invalid vehicle ID."});const id=req.params.id;const [vehicle,trips,assignments,maintenance,workOrders,schedules,fuel,expenses,tripExpenses,driverExpenses,audits]=await Promise.all([Vehicle.findById(id).populate("ownerId","fullName email").lean(),Trip.find({vehicle:id}).populate("driver","fullName").populate("customer","fullName").sort({scheduledStart:-1}).limit(200).lean(),Assignment.find({vehicle:id}).populate("driver","fullName").populate("assignedBy","fullName").sort({assignedAt:-1}).limit(200).lean(),MaintenanceRecord.find({vehicle:id}).sort({completionDate:-1,createdAt:-1}).limit(200).lean(),MaintenanceWorkOrder.find({vehicle:id}).sort({createdAt:-1}).limit(200).lean(),MaintenanceSchedule.find({vehicle:id}).sort({nextServiceDate:-1}).limit(100).lean(),FuelExpense.find({vehicle:id}).populate("driver","fullName").populate("trip","tripId").sort({fuelDate:-1}).limit(200).lean(),Expense.find({vehicle:id}).populate("driver","fullName").populate("trip","tripId").sort({expenseDate:-1}).limit(200).lean(),TripExpense.find({vehicle:id}).populate("driver","fullName").populate("trip","tripId").sort({expenseDate:-1}).limit(200).lean(),DriverExpense.find({vehicle:id}).populate("driver","fullName").populate("trip","tripId").sort({expenseDate:-1}).limit(200).lean(),AuditLog.find({resource:"VEHICLE",recordId:id}).populate("actor","fullName role").sort({createdAt:-1}).limit(200).lean()]);if(!vehicle)return res.status(404).json({success:false,message:"Vehicle not found."});const events=[...trips.map(x=>({date:x.updatedAt||x.createdAt,type:"TRIP",text:`Trip ${x.tripId} — ${x.tripStatus}`,trip:x})),...assignments.map(x=>({date:x.assignedAt||x.createdAt,type:"ASSIGNMENT",text:`Driver ${x.driver?.fullName||"—"} assigned`,assignment:x})),...maintenance.map(x=>({date:x.completionDate||x.createdAt,type:"MAINTENANCE",text:`${x.serviceType} completed`,maintenance:x})),...workOrders.map(x=>({date:x.updatedAt||x.createdAt,type:"WORK_ORDER",text:`Maintenance work order ${x.status}`})),...audits.map(x=>({date:x.createdAt,type:"AUDIT",text:`${x.action} by ${x.actor?.fullName||"System"}`}))].sort((a,b)=>new Date(b.date)-new Date(a.date));return res.json({success:true,vehicle,trips,assignments,maintenance,workOrders,schedules,fuel,expenses,tripExpenses,driverExpenses,events});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load vehicle history."});}}
async function driverPerformance(req,res){try{const drivers=await User.find({role:"DRIVER"}).select("fullName email isActive accountStatus").lean();const ids=drivers.map(x=>x._id);const stats=await Trip.aggregate([{$match:{driver:{$in:ids}}},{$group:{_id:"$driver",total:{$sum:1},completed:{$sum:{$cond:[{$eq:["$tripStatus","COMPLETED"]},1,0]}},cancelled:{$sum:{$cond:[{$eq:["$tripStatus","CANCELLED"]},1,0]}},delayed:{$sum:{$cond:[{$and:[{$ne:["$tripStatus","COMPLETED"]},{$regexMatch:{input:{$ifNull:["$notes",""]},regex:"delay",options:"i"}}]},1,0]}}}}]);const map=new Map(stats.map(x=>[String(x._id),x]));return res.json({success:true,drivers:drivers.map(d=>{const x=map.get(String(d._id))||{};const total=Number(x.total||0);return {...d,totalTrips:total,completedTrips:Number(x.completed||0),cancelledTrips:Number(x.cancelled||0),delayedTrips:Number(x.delayed||0),completionRate:total?x.completed/total*100:0,cancellationRate:total?x.cancelled/total*100:0,delayRate:total?x.delayed/total*100:0};})});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load driver performance."});}}
module.exports={liveFleet,vehicleHistory,driverPerformance};