const express = require("express");
const { authenticate, authorize } = require("../middleware/authMiddleware");
const c = require("../controllers/maintenanceController");
const router = express.Router();
const access = [authenticate, authorize("MAINTENANCE_MANAGER")];
router.get("/dashboard", ...access, c.dashboard);
router.get("/requests", ...access, c.requests);
router.get("/requests/:id", ...access, c.getRequest);
router.put("/requests/:id/status", ...access, c.updateRequestStatus);
router.get("/work-orders", ...access, c.workOrders);
router.post("/work-orders", ...access, c.createWorkOrder);
router.get("/work-orders/:id", ...access, c.getWorkOrder);
router.put("/work-orders/:id", ...access, c.updateWorkOrder);
router.post("/work-orders/:id/start", ...access, c.startWorkOrder);
router.post("/work-orders/:id/complete", ...access, c.completeWorkOrder);
router.post("/work-orders/:id/release", ...access, c.releaseWorkOrder);
router.get("/vehicles", ...access, c.vehicles);
router.get("/schedules", ...access, c.schedules);
router.post("/schedules", ...access, c.createSchedule);
router.put("/schedules/:id", ...access, c.updateSchedule);
router.delete("/schedules/:id", ...access, c.deleteSchedule);
router.get("/history", ...access, c.history);
router.get("/costs", ...access, c.costs);
router.get("/profile", ...access, c.profile);
router.put("/profile", ...access, c.updateProfile);
module.exports = router;
