const express = require("express");
const { getTrips, getTrip, createTrip, updateTrip, startTrip, completeTrip, cancelTrip } = require("../controllers/tripController");
const { authenticate, authorize } = require("../middleware/authMiddleware");
const router = express.Router();
const access = [authenticate, authorize("FLEET_MANAGER", "SUPER_ADMIN")];
router.get("/", ...access, getTrips);
router.get("/:id", ...access, getTrip);
router.post("/", ...access, createTrip);
router.put("/:id", ...access, updateTrip);
router.patch("/:id/start", ...access, startTrip);
router.patch("/:id/complete", ...access, completeTrip);
router.patch("/:id/cancel", ...access, cancelTrip);
module.exports = router;
