import { useState } from "react";
import { ArrowLeft, Lock, ShieldCheck, Truck } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { apiRequest } from "../services/api";
import "../Auth.css";

export default function ChangePassword(){
  const navigate=useNavigate(); const [currentPassword,setCurrentPassword]=useState(""); const [password,setPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  const submit=async e=>{e.preventDefault();setError("");setMessage("");if(password.length<8||!/[A-Za-z]/.test(password)||!/\d/.test(password))return setError("New password must be at least 8 characters and contain a letter and number.");if(password!==confirmPassword)return setError("Password and confirm password do not match.");try{setLoading(true);const r=await apiRequest("/api/auth/change-password",{method:"POST",body:JSON.stringify({currentPassword,password,confirmPassword})});setMessage(r.message||"Password changed successfully.");setCurrentPassword("");setPassword("");setConfirmPassword("");}catch(e){setError(e.message||"Unable to change password.")}finally{setLoading(false)}};
  return <div className="auth-page"><div className="auth-background"/><div className="auth-wrapper"><button type="button" className="back-home-btn" onClick={()=>navigate(-1)}><ArrowLeft size={18}/> Back</button><div className="auth-card"><div className="auth-brand"><div className="auth-logo-icon"><Truck size={23}/></div><span>Fleet<span>Flow</span></span></div><div className="auth-heading"><div className="auth-heading-icon"><ShieldCheck size={25}/></div><h1>Change Password</h1><p>Update your FleetFlow account password securely.</p></div>{error&&<div className="auth-server-error" role="alert">{error}</div>}{message&&<div className="auth-success-message" role="status">{message}</div>}<form className="auth-form" onSubmit={submit} noValidate><div className="auth-field"><label>Current Password</label><div className="auth-input"><Lock size={18}/><input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required/></div></div><div className="auth-field"><label>New Password</label><div className="auth-input"><Lock size={18}/><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div></div><div className="auth-field"><label>Confirm New Password</label><div className="auth-input"><Lock size={18}/><input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></div></div><button className="auth-submit-btn" disabled={loading}>{loading?"Changing...":"Change Password"}</button></form><p className="auth-switch"><Link to="/login">Return to Login</Link></p></div></div></div>;
}
