import { useCallback,useEffect,useState } from "react";
import { Eye, MapPin, RefreshCw, Search } from "lucide-react";
import { Link,useNavigate } from "react-router-dom";
import { apiRequest } from "../services/api";
import CustomerLayout from "./CustomerLayout";
import "./CustomerDashboard.css";
const date=(v)=>v?new Date(v).toLocaleString("en-IN"):"—";const badge=(v)=>String(v||"").toLowerCase().replaceAll("_","-");
export default function CustomerTrips(){const [trips,setTrips]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[dateFilter,setDateFilter]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[page,setPage]=useState(1),[pagination,setPagination]=useState(null);const load=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams();if(search)q.set("search",search);if(status)q.set("status",status);if(dateFilter)q.set("date",dateFilter);q.set("page",page);q.set("limit",20);const r=await apiRequest(`/api/customer/trips?${q.toString()}`);setTrips(r.trips||[]);setPagination(r.pagination||null)}catch(e){setError(e.message)}finally{setLoading(false)}},[search,status,dateFilter,page]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
useEffect(()=>{setPage(1)},[search,status,dateFilter]);const navigate=useNavigate();return <CustomerLayout title="My Trips" subtitle="Trips assigned to your customer account"><div className="customer-toolbar"><div><h2>My Trips</h2><p>Only trips belonging to your account are shown.</p></div><button className="customer-button" onClick={load} disabled={loading}><RefreshCw size={16}/> Refresh</button></div>{error&&<div className="customer-alert error">{error}</div>}<section className="customer-card"><div className="customer-actions" style={{marginBottom:16}}><div className="customer-button" style={{flex:"2 1 280px",justifyContent:"flex-start"}}><Search size={17}/><input style={{border:0,outline:0,flex:1,font: "inherit"}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search trip, pickup or destination..."/></div><select className="customer-button" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option>{["SCHEDULED","ASSIGNED","IN_PROGRESS","PAUSED","COMPLETED","CANCELLED"].map(s=><option key={s}>{s.replaceAll("_"," ")}</option>)}</select><input className="customer-button" type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/></div>{loading?<div className="customer-loading"><div className="customer-loading-inner"><div className="customer-spinner"/>Loading trips...</div></div>:<div className="customer-table-wrap"><table className="customer-table"><thead><tr><th>Trip ID</th><th>Route</th><th>Driver</th><th>Vehicle</th><th>Scheduled</th><th>Distance</th><th>Status</th><th>Action</th></tr></thead><tbody>{trips.length?trips.map(t=><tr key={t._id}><td><strong>{t.tripId}</strong></td><td>{t.pickupLocation} → {t.destination}</td><td>{t.driver?.fullName||"Unassigned"}</td><td>{t.vehicle?.registrationNumber||"Unassigned"}</td><td>{date(t.scheduledStart)}</td><td>{Number(t.distance||0).toLocaleString("en-IN")} km</td><td><span className={`customer-badge ${badge(t.tripStatus)}`}>{t.tripStatus.replaceAll("_"," ")}</span></td><td><div className="customer-actions-inline"><button className="customer-button" onClick={()=>navigate(`/customer/trips/${t._id}`)}><Eye size={14}/> View</button>{["IN_PROGRESS","PAUSED"].includes(t.tripStatus)&&<Link className="customer-button" to={`/customer/tracking/${t._id}`}><MapPin size={14}/> Track</Link>}</div></td></tr>):<tr><td colSpan="8" className="customer-empty">No trips found.</td></tr>}</tbody></table></div>}{pagination&&<div className="customer-actions" style={{justifyContent:"flex-end",marginTop:14}}><button className="customer-button" disabled={!pagination.hasPrevPage} onClick={()=>setPage(page-1)}>Previous</button><span className="customer-muted">Page {pagination.page} of {Math.max(1,pagination.totalPages)}</span><button className="customer-button" disabled={!pagination.hasNextPage} onClick={()=>setPage(page+1)}>Next</button></div>}</section></CustomerLayout>}
