import { useState } from "react";
import { CheckCircle2, Send } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { apiRequest } from "../services/api";
import CustomerLayout from "./CustomerLayout";
import "./CustomerDashboard.css";

const services = ["Passenger Transportation", "Cargo Transportation", "Goods Delivery", "Full Truck Load", "Other"];

export default function CustomerTripRequest() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ pickupLocation:"", destination:"", requestedDate:"", requestedTime:"", serviceType:"Passenger Transportation", vehicleType:"", passengerCount:"", cargoDetails:"", cargoWeight:"", quantity:"", specialInstructions:"" });
  const [loading,setLoading]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const change=(e)=>setForm(f=>({...f,[e.target.name]:e.target.value}));
  const submit=async(e)=>{e.preventDefault();setLoading(true);setError("");setSuccess("");try{const r=await apiRequest("/api/customer/trip-requests",{method:"POST",body:JSON.stringify({...form,passengerCount:Number(form.passengerCount||0),cargoWeight:Number(form.cargoWeight||0),quantity:Number(form.quantity||0)})});setSuccess(r.message);setForm({pickupLocation:"",destination:"",requestedDate:"",requestedTime:"",serviceType:"Passenger Transportation",vehicleType:"",passengerCount:"",cargoDetails:"",cargoWeight:"",quantity:"",specialInstructions:""});setTimeout(()=>navigate("/customer/trips"),700);}catch(x){setError(x.message);}finally{setLoading(false)}};
  return <CustomerLayout title="Trip Request" subtitle="Request transportation services from FleetFlow"><div className="customer-toolbar"><div><h2>New Trip Request</h2><p>Your request is reviewed before a vehicle or driver is assigned.</p></div></div>{error&&<div className="customer-alert error">{error}</div>}{success&&<div className="customer-alert success"><CheckCircle2 size={16}/> {success}</div>}<section className="customer-card"><form className="customer-form" onSubmit={submit}><label>Pickup Location<input name="pickupLocation" required value={form.pickupLocation} onChange={change} placeholder="e.g. Guntur"/></label><label>Destination<input name="destination" required value={form.destination} onChange={change} placeholder="e.g. Hyderabad"/></label><label>Requested Date<input name="requestedDate" required type="date" value={form.requestedDate} onChange={change}/></label><label>Requested Time<input name="requestedTime" required type="time" value={form.requestedTime} onChange={change}/></label><label>Service Type<select name="serviceType" value={form.serviceType} onChange={change}>{services.map(x=><option key={x}>{x}</option>)}</select></label><label>Vehicle Type / Requirement<input name="vehicleType" value={form.vehicleType} onChange={change} placeholder="e.g. Truck, Van, Bus"/></label><label>Passenger Count<input name="passengerCount" min="0" type="number" value={form.passengerCount} onChange={change}/></label><label>Cargo Weight<input name="cargoWeight" min="0" step="0.01" type="number" value={form.cargoWeight} onChange={change} placeholder="kg / project unit"/></label><label>Quantity<input name="quantity" min="0" type="number" value={form.quantity} onChange={change}/></label><label className="full">Cargo Details<textarea name="cargoDetails" value={form.cargoDetails} onChange={change} placeholder="Cargo type, goods details, dimensions, etc."/></label><label className="full">Special Instructions<textarea name="specialInstructions" value={form.specialInstructions} onChange={change} placeholder="Any pickup, delivery or service instructions"/></label><div className="customer-form-actions"><button className="customer-button primary" disabled={loading}><Send size={16}/>{loading?"Submitting...":"Submit Trip Request"}</button></div></form></section></CustomerLayout>;
}
