import {useCallback,useEffect,useState} from "react";
import {Fuel,RefreshCw,Wrench,Receipt,Plus,X} from "lucide-react";
import DriverLayout from "./DriverLayout";
import {apiRequest} from "../services/api";
import "./DriverDashboard.css";
const money=v=>`₹${Number(v||0).toLocaleString("en-IN")}`;
const date=v=>v?new Date(v).toLocaleDateString():"—";
export default function DriverRecords(){
 const [d,setD]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("fuel"),[show,setShow]=useState(false),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({category:"FUEL",amount:"",expenseDate:new Date().toISOString().slice(0,10),vehicle:"",trip:"",description:"",receiptNumber:"",notes:""});
 const load=useCallback(async()=>{setLoading(true);setError("");try{setD(await apiRequest("/api/driver/records"))}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{const r=await apiRequest("/api/driver/expenses/submit",{method:"POST",body:JSON.stringify(form)});setShow(false);setForm({...form,amount:"",description:"",receiptNumber:"",notes:""});await load();alert(r.message)}catch(e){setError(e.message)}finally{setSaving(false)}};
 const rows=tab==="fuel"?d?.fuel||[]:tab==="maintenance"?d?.maintenance||[]:d?.expenses||[];
 return <DriverLayout title="Vehicle Records & Expenses" subtitle="Your authorized vehicle fuel, maintenance and expense history">
  <div className="driver-toolbar"><div><h2>Vehicle Records</h2><p>Only records linked to your authorized vehicle(s) are shown.</p></div><div><button className="driver-button" onClick={load}><RefreshCw size={16}/> Refresh</button> <button className="driver-button primary" onClick={()=>setShow(true)}><Plus size={16}/> Submit Expense</button></div></div>
  {error&&<div className="driver-alert error">{error}</div>}
  {loading?<div className="driver-loading">Loading vehicle records...</div>:<>
   <div className="driver-cards"><div className="driver-card"><div className="driver-card-icon"><Fuel size={19}/></div><div><span>Total Fuel Cost</span><strong>{money(d?.totals?.fuelCost)}</strong></div></div><div className="driver-card"><div className="driver-card-icon"><Fuel size={19}/></div><div><span>Fuel Quantity</span><strong>{Number(d?.totals?.fuelQuantity||0).toFixed(2)} L</strong></div></div><div className="driver-card"><div className="driver-card-icon"><Wrench size={19}/></div><div><span>Maintenance Cost</span><strong>{money(d?.totals?.maintenanceCost)}</strong></div></div><div className="driver-card"><div className="driver-card-icon"><Receipt size={19}/></div><div><span>Vehicle Expenses</span><strong>{money(d?.totals?.vehicleExpenses)}</strong></div></div></div>
   <div className="driver-panel"><div className="driver-toolbar"><div><h2>{tab==="fuel"?"Fuel History":tab==="maintenance"?"Maintenance History":"Vehicle Expense History"}</h2></div><div><button className="driver-button" onClick={()=>setTab("fuel")}><Fuel size={15}/> Fuel</button><button className="driver-button" onClick={()=>setTab("maintenance")}><Wrench size={15}/> Maintenance</button><button className="driver-button" onClick={()=>setTab("expenses")}><Receipt size={15}/> Expenses</button></div></div>
    <div className="driver-table-wrap"><table className="driver-table"><thead>{tab==="fuel"?<tr><th>Date</th><th>Vehicle</th><th>Fuel Type</th><th>Quantity</th><th>Amount</th><th>Odometer</th><th>Trip</th></tr>:tab==="maintenance"?<tr><th>Service Date</th><th>Vehicle</th><th>Service Type</th><th>Description</th><th>Cost</th><th>Status</th></tr>:<tr><th>Date</th><th>Type</th><th>Amount</th><th>Vehicle</th><th>Trip</th><th>Status</th><th>Description</th></tr>}</thead><tbody>{rows.map((x,i)=>tab==="fuel"?<tr key={x._id||i}><td>{date(x.fuelDate)}</td><td>{x.vehicle?.registrationNumber||"—"}</td><td>{x.fuelType}</td><td>{x.litres} L</td><td>{money(x.totalAmount)}</td><td>{x.odometer??"—"}</td><td>{x.trip?.tripId||"—"}</td></tr>:tab==="maintenance"?<tr key={x._id||i}><td>{date(x.completionDate||x.startDate||x.createdAt)}</td><td>{x.vehicle?.registrationNumber||"—"}</td><td>{x.serviceType||"—"}</td><td>{x.description||"—"}</td><td>{money(x.totalCost)}</td><td>{x.status||"COMPLETED"}</td></tr>:<tr key={x._id||i}><td>{date(x.date)}</td><td>{x.expenseType||x.category}</td><td>{money(x.amount)}</td><td>{x.vehicle?.registrationNumber||"—"}</td><td>{x.trip?.tripId||"—"}</td><td>{x.status||"—"}</td><td>{x.description||"—"}</td></tr>)}{!rows.length&&<tr><td colSpan="7" className="driver-empty">No records found.</td></tr>}</tbody></table></div>
   </div></>}
  {show&&<div className="driver-modal-backdrop"><div className="driver-modal"><div className="driver-toolbar"><h2>Submit Expense</h2><button className="driver-button" onClick={()=>setShow(false)}><X size={16}/></button></div><form className="driver-form" onSubmit={submit}><label>Expense Type<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>FUEL</option><option>TOLL</option><option>PARKING</option><option>OTHER</option></select></label><label>Amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Date<input required type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></label><label>Vehicle<select value={form.vehicle} onChange={e=>setForm({...form,vehicle:e.target.value})}><option value="">Auto-select authorized vehicle</option>{(d?.vehicles||[]).map(v=><option key={v._id} value={v._id}>{v.registrationNumber}</option>)}</select></label><label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Receipt Number<input value={form.receiptNumber} onChange={e=>setForm({...form,receiptNumber:e.target.value})}/></label><div><button type="button" className="driver-button" onClick={()=>setShow(false)}>Cancel</button><button className="driver-button primary" disabled={saving}>{saving?"Submitting...":"Submit Expense"}</button></div></form></div></div>}
 </DriverLayout>
}
