import { useCallback, useEffect, useState } from "react";
import { Activity, Car, CheckCircle, RefreshCw, Users, Wrench, Clock, Truck } from "lucide-react";
import FleetManagerLayout from "./FleetManagerLayout";
import { apiRequest } from "../services/api";

const n = v => Number(v || 0);
export default function FleetManagerDashboard() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await apiRequest("/api/fleet-manager/dashboard")); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const k = data?.kpis || {};
  const cards = [[Car,"Total Vehicles",n(k.totalVehicles)],[CheckCircle,"Available Vehicles",n(k.availableVehicles)],[Truck,"Vehicles On Trip",n(k.vehiclesOnTrip)],[Wrench,"In Maintenance",n(k.vehiclesInMaintenance)],[Users,"Total Drivers",n(k.totalDrivers)],[Users,"Available Drivers",n(k.availableDrivers)],[Activity,"Drivers On Trip",n(k.driversOnTrip)],[Activity,"Active Trips",n(k.activeTrips)],[Clock,"Scheduled Trips",n(k.scheduledTrips)],[CheckCircle,"Completed Trips",n(k.completedTrips)]];
  return <FleetManagerLayout title="Fleet Manager Dashboard" subtitle="Monitor and manage real-time fleet operations"><div className="fm-toolbar"><div><h2>Operations Overview</h2><p>Live metrics from MongoDB</p></div><button onClick={load} disabled={loading}><RefreshCw size={16}/> Refresh</button></div>{error && <div className="fm-alert error">{error}</div>}{loading && !data ? <div className="fm-loading"><div className="spinner"/> Loading fleet data...</div> : <><div className="fm-stats">{cards.map(([Icon,label,value]) => <div className="fm-stat" key={label}><div className="fm-stat-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong></div></div>)}</div><div className="fm-grid-2"><section className="fm-card"><h2>Vehicle Status</h2>{Object.entries(data?.vehicleStatus || {}).map(([s,c]) => <div className="fm-row" key={s}><span>{s.replaceAll("_"," ")}</span><strong>{c}</strong></div>)}</section><section className="fm-card"><h2>Driver Status</h2>{Object.entries(data?.driverStatus || {}).map(([s,c]) => <div className="fm-row" key={s}><span>{s.replaceAll("_"," ")}</span><strong>{c}</strong></div>)}</section></div><section className="fm-card"><div className="fm-card-head"><h2>Recent Trips</h2><button onClick={() => location.href="/fleet-manager/trips"}>View all</button></div><div className="fm-table-wrap"><table className="fm-table"><thead><tr><th>Trip</th><th>Route</th><th>Vehicle</th><th>Driver</th><th>Status</th></tr></thead><tbody>{(data?.recentTrips || []).map(t => <tr key={t._id}><td>{t.tripId}</td><td>{t.pickupLocation} → {t.destination}</td><td>{t.vehicle?.registrationNumber || "—"}</td><td>{t.driver?.fullName || "—"}</td><td><span className={`fm-badge ${t.tripStatus.toLowerCase().replaceAll("_","-")}`}>{t.tripStatus.replaceAll("_"," ")}</span></td></tr>)}{!data?.recentTrips?.length && <tr><td colSpan="5" className="fm-empty">No trips found.</td></tr>}</tbody></table></div></section><section className="fm-card"><h2>Current Vehicle Assignments</h2><div className="fm-table-wrap"><table className="fm-table"><thead><tr><th>Vehicle</th><th>Driver</th><th>Status</th><th>Assigned</th></tr></thead><tbody>{(data?.assignments || []).map(a => <tr key={a._id}><td>{a.vehicle?.registrationNumber || "—"}</td><td>{a.driver?.fullName || "—"}</td><td>{a.vehicle?.status || "—"}</td><td>{new Date(a.assignedAt).toLocaleString()}</td></tr>)}{!data?.assignments?.length && <tr><td colSpan="4" className="fm-empty">No active assignments.</td></tr>}</tbody></table></div></section></>}</FleetManagerLayout>;
}
