const PAGE_WIDTH = 842;
const PAGE_HEIGHT = 595;
const MARGIN = 28;
const FONT_SIZE = 8;
const LINE_HEIGHT = 11;
const HEADER_HEIGHT = 24;
const CELL_PAD = 4;

const escapePdfText = (value) => String(value ?? "")
  .replace(/₹/g, "INR ")
  .replace(/[^ -~]/g, "?")
  .replace(/\\/g, "\\\\")
  .replace(/\(/g, "\\(")
  .replace(/\)/g, "\\)")
  .replace(/\r?\n/g, " ");

const plainValue = (value) => {
  if (value == null) return "";
  if (typeof value === "object") {
    try { return JSON.stringify(value); } catch { return String(value); }
  }
  return String(value);
};

const wrapText = (text, maxChars) => {
  const value = plainValue(text);
  if (!value) return [""];
  const words = value.split(/\s+/);
  const lines = [];
  let line = "";
  words.forEach((word) => {
    if (!line) {
      if (word.length <= maxChars) line = word;
      else {
        for (let i = 0; i < word.length; i += maxChars) lines.push(word.slice(i, i + maxChars));
        line = "";
      }
    } else if ((line.length + word.length + 1) <= maxChars) {
      line += ` ${word}`;
    } else {
      lines.push(line);
      line = word.length <= maxChars ? word : "";
      if (word.length > maxChars) {
        for (let i = 0; i < word.length; i += maxChars) {
          const chunk = word.slice(i, i + maxChars);
          if (chunk.length === maxChars || i + maxChars >= word.length) {
            if (i + maxChars >= word.length) line = chunk;
            else lines.push(chunk);
          }
        }
      }
    }
  });
  if (line) lines.push(line);
  return lines.length ? lines : [""];
};

const makeWidths = (headers, rows) => {
  const sample = rows.slice(0, 80);
  const widths = headers.map((header, index) => {
    const max = Math.max(
      String(header).length,
      ...sample.map(row => plainValue(row[index]).length > 45 ? 45 : plainValue(row[index]).length)
    );
    return Math.max(55, Math.min(150, max * 4.2 + CELL_PAD * 2));
  });
  const available = PAGE_WIDTH - MARGIN * 2;
  const total = widths.reduce((a, b) => a + b, 0);
  if (total <= available) return widths;
  const scale = available / total;
  return widths.map(width => Math.max(42, width * scale));
};

const createPageContent = (title, headers, rows, widths, pageRows, pageNumber, totalPages) => {
  const commands = [];
  const xPositions = [MARGIN];
  widths.forEach(width => xPositions.push(xPositions[xPositions.length - 1] + width));
  const tableWidth = widths.reduce((a, b) => a + b, 0);

  commands.push("0.12 0.16 0.22 rg");
  commands.push(`BT /F1 15 Tf ${MARGIN} ${PAGE_HEIGHT - 32} Td (${escapePdfText(title)}) Tj ET`);
  commands.push("0 g");
  commands.push(`BT /F1 7 Tf ${PAGE_WIDTH - 95} ${PAGE_HEIGHT - 30} Td (${pageNumber}/${totalPages}) Tj ET`);

  let y = PAGE_HEIGHT - 62;
  const drawRow = (cells, header = false) => {
    const maxLines = Math.max(...cells.map((cell, i) => wrapText(cell, Math.max(8, Math.floor((widths[i] - CELL_PAD * 2) / 4.1))).length));
    const rowHeight = Math.max(HEADER_HEIGHT, maxLines * LINE_HEIGHT + CELL_PAD * 2);
    if (header) {
      commands.push("0.88 0.90 0.94 rg");
      commands.push(`${MARGIN} ${y - rowHeight + 3} ${tableWidth} ${rowHeight} re f`);
      commands.push("0 g");
    }
    commands.push("0.72 G 0.5 w");
    commands.push(`${MARGIN} ${y - rowHeight + 3} ${tableWidth} ${rowHeight} re S`);
    for (let i = 1; i < xPositions.length - 1; i++) {
      commands.push(`${xPositions[i]} ${y - rowHeight + 3} m ${xPositions[i]} ${y + 3} l S`);
    }
    cells.forEach((cell, i) => {
      const lines = wrapText(cell, Math.max(8, Math.floor((widths[i] - CELL_PAD * 2) / 4.1)));
      lines.forEach((line, lineIndex) => {
        const textY = y - 10 - lineIndex * LINE_HEIGHT;
        commands.push(`BT /F1 ${header ? 7.5 : FONT_SIZE} Tf ${xPositions[i] + CELL_PAD} ${textY} Td (${escapePdfText(line)}) Tj ET`);
      });
    });
    y -= rowHeight;
    return rowHeight;
  };

  drawRow(headers, true);
  pageRows.forEach(row => drawRow(row));
  commands.push("0.35 g");
  commands.push(`BT /F1 7 Tf ${MARGIN} 18 Td (${escapePdfText(`Generated by FleetFlow · ${new Date().toLocaleString()}`)}) Tj ET`);
  return commands.join("\n");
};

const buildPdf = (title, headers, rows) => {
  const safeHeaders = headers.map((h) => plainValue(h));
  const safeRows = rows.map((row) =>
    safeHeaders.map((_, i) => plainValue(row?.[i]))
  );

  const widths = makeWidths(safeHeaders, safeRows);
  const availableHeight = PAGE_HEIGHT - 95;
  const estimatedRowsPerPage = Math.max(1, Math.floor(availableHeight / 30));
  const chunks = [];

  for (let i = 0; i < safeRows.length; i += estimatedRowsPerPage) {
    chunks.push(safeRows.slice(i, i + estimatedRowsPerPage));
  }

  if (!chunks.length) chunks.push([]);

  const totalPages = chunks.length;
  const objects = [];

  const addObject = (body) => {
    objects.push(body);
    return objects.length;
  };

  const catalogId = addObject("");
  const pagesId = addObject("");
  const fontId = addObject(
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>"
  );

  const pageIds = [];

  chunks.forEach((chunk, index) => {
    const content = createPageContent(
      title,
      safeHeaders,
      safeRows,
      widths,
      chunk,
      index + 1,
      totalPages
    );

    // PDF stream Length must be the number of bytes, not JavaScript characters.
    const contentLength = new TextEncoder().encode(content).length;

    const contentId = addObject(
      `<< /Length ${contentLength} >>\nstream\n${content}\nendstream`
    );

    const pageId = addObject(
      `<< /Type /Page /Parent ${pagesId} 0 R ` +
      `/MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] ` +
      `/Resources << /Font << /F1 ${fontId} 0 R >> >> ` +
      `/Contents ${contentId} 0 R >>`
    );

    pageIds.push(pageId);
  });

  objects[catalogId - 1] =
    `<< /Type /Catalog /Pages ${pagesId} 0 R >>`;

  objects[pagesId - 1] =
    `<< /Type /Pages /Kids [` +
    `${pageIds.map((id) => `${id} 0 R`).join(" ")}` +
    `] /Count ${pageIds.length} >>`;

  /*
   * IMPORTANT:
   * PDF xref/startxref values are BYTE OFFSETS.
   * Using JavaScript string .length can create invalid PDFs when
   * non-ASCII characters are present. Build the PDF from UTF-8 bytes
   * and calculate every offset from the actual encoded byte length.
   *
   * See the PDF specification's requirement that xref/startxref use
   * byte offsets from the beginning of the file.
   */
  const encoder = new TextEncoder();
  const byteLength = (value) => encoder.encode(value).length;

  // Keep the file header ASCII so its byte length is deterministic.
  let pdf = "%PDF-1.4\n%\n";
  const offsets = [0];

  let currentOffset = byteLength(pdf);

  objects.forEach((object, index) => {
    offsets.push(currentOffset);

    const objectText =
      `${index + 1} 0 obj\n` +
      `${object}\n` +
      `endobj\n`;

    pdf += objectText;
    currentOffset += byteLength(objectText);
  });

  const xrefOffset = currentOffset;

  pdf +=
    `xref\n` +
    `0 ${objects.length + 1}\n` +
    `0000000000 65535 f \n`;

  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }

  pdf +=
    `trailer\n` +
    `<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\n` +
    `startxref\n` +
    `${xrefOffset}\n` +
    `%%EOF`;

  return new Blob([encoder.encode(pdf)], {
    type: "application/pdf",
  });
};

export function downloadTablePdf(title, headers, rows, filename) {
  const blob = buildPdf(title, headers, rows);
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function parseCsv(csv) {
  const rows = [];
  let row = [], value = "", quoted = false;
  for (let i = 0; i < csv.length; i++) {
    const char = csv[i];
    const next = csv[i + 1];
    if (char === '"' && quoted && next === '"') { value += '"'; i++; continue; }
    if (char === '"') { quoted = !quoted; continue; }
    if (char === "," && !quoted) { row.push(value); value = ""; continue; }
    if ((char === "\n" || char === "\r") && !quoted) {
      if (char === "\r" && next === "\n") i++;
      row.push(value); value = "";
      if (row.some(cell => cell !== "")) rows.push(row);
      row = [];
      continue;
    }
    value += char;
  }
  if (value.length || row.length) { row.push(value); if (row.some(cell => cell !== "")) rows.push(row); }
  return rows;
}
